sudo: required
services:
  - docker

before_install:
  - docker build -t darkknightdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true darkknightdocker/react-test npm test

after_success:
  - docker build -t darkknightdocker/multi-client ./client
  - docker build -t darkknightdocker/multi-nginx ./nginx
  - docker build -t darkknightdocker/multi-server ./server
  - docker build -t darkknightdocker/multi-worker ./worker
  # Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push those images to docker hub test
  - docker push darkknightdocker/multi-client 
  - docker push darkknightdocker/multi-nginx 
  - docker push darkknightdocker/multi-server 
  - docker push darkknightdocker/multi-worker 
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-582711349568
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
