sudo: required
services:
  - docker

before_install:
  - docker build -t darkknightdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true darkknightdocker/react-test npm test

after_success:
  - docker build -t darkknightdocker/multi-client ./client
  - docker build -t darkknightdocker/multi-nginx ./nginx
  - docker build -t darkknightdocker/multi-server ./server
  - docker build -t darkknightdocker/multi-worker ./worker
  # Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push those images to docker hub
  - docker push darkknightdocker/multi-client ./client
  - docker push darkknightdocker/multi-nginx ./nginx
  - docker push darkknightdocker/multi-server ./server
  - docker push darkknightdocker/multi-worker ./worker